# Generated by Django 4.2.3 on 2023-07-29 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('fed_tax_id', models.CharField(max_length=9)),
                ('reg_state', models.CharField(max_length=2)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=9)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
